### ISSUE TITLE
consequentially?

### ISSUE THREAD

**Issue by mbunyan** [yiisoft/rate-limiter#2]
In description, did you mean 'number of *subsequent* requests', rather than 'consequently'?

But then I may be misreading the intentioned functionality.

 Interesting to see this kind of functionality being clearly exposed for implementation.
Mike B

**Comment by samdark** [comment]
"consequentially" is correct word there (and it's not "consequently") meaning that requests are made one by one.

Likely readme should be updated. Interesting info to be included:

- https://github.com/yiisoft/rate-limiter/blob/master/src/Middleware.php#L15
- https://github.com/yiisoft/rate-limiter/blob/master/src/Counter.php#L10
