### ISSUE TITLE
Concurrent request issues

### ISSUE THREAD

**Issue by jiaweipan** [yiisoft/rate-limiter#41]
When concurrent requests are made, flow restriction cannot be applied.
for example,When using caching such as Apcu or Redis, it relies on "TheoreticalNextIncrementTime",It may be dirty reading.

**Comment by jiaweipan** [comment]
reopen

**Comment by jiaweipan** [comment]
misoperation

**Comment by samdark** [comment]
Could be, yes. Have you actually experinced that? Any idea about the fix? I don't see how this operation could be made atomic.

**Comment by rustamwin** [comment]
What about using mutex?

**Comment by jiaweipan** [comment]
Using the atomic features of APCU to support concurrency security， #43 it has implemented this feature.

**Comment by samdark** [comment]
@rustamwin likely that would hurt possibility handling any significant bandwidth. I'm not sure about it though.

**Comment by jiaweipan** [comment]
@samdark The non concurrent secure "SimpleCacheStorage" version remains unchanged.It can still be customized and extended.

**Comment by samdark** [comment]
@jiaweipan worth noting the difference either in readme or in phpdoc.
