### ISSUE TITLE
PSR ClockInterface instead of TimerInterface

### ISSUE THREAD

**Issue by xepozz** [yiisoft/rate-limiter#44]
Should we replace `\Yiisoft\Yii\RateLimiter\Time\TimerInterface` with the one from https://www.php-fig.org/psr/psr-20?

**Comment by vjik** [comment]
~~PSR-20 work with `DateTimeImmutable` that not support milliseconds.~~

**Comment by xepozz** [comment]
> PSR-20 work with `DateTimeImmutable` that not support milliseconds.

https://3v4l.org/M5JrY

**Comment by vjik** [comment]
I like this idea.

**Comment by samdark** [comment]
Since there's a performance drop and this is heavily used middleware, decided not to do it.
